<?php

namespace Database\Seeders;

use App\Models\Plant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plants = [
            [
                'name' => 'Mentha-Mint',
                'botanical_name' => 'Mentha-Mint',
                'scientific_name' => 'Mentha-Mint',
                'also_known_as' => json_encode(['Spearmint', 'Peppermint']),
                'description' => 'Mint is an aromatic plant that is almost entirely perennial.Thery have widely spread underground branching stems.',
                'genus_id'=> 1,
                'family_id'=>1 ,
                'order_id'=>1 ,
                'group_id'=>1 ,
                'phylum_id'=>1 ,
                'type_id'=>1 ,
                'drainage_id'=>1 ,
                'section_id'=>2,
                'toughness'=>"High",
                'maintenance'=>"Medium",
                'sunlight'=>"Full Sun",
                'hardness_zone'=>"3-9",
                'min_ph'=>6.0,
                'max_ph'=>7.0,
                'min_tp' => 10,
                'ideal_min_tp' =>35,
                'ideal_max_tp'=>45,
                'max_tp' => 50,
                'water'=>"Every 2-3 Days",
                'repotting'=>"Every 1-2 Years",
                'fertilizer'=>"Once a month",
                'misting'=>"Hot, Dry Climates",
                'pruning' =>'Spring, Summer',
                'uses' => "Mint (Mentha) is a versatile herb widely used for its refreshing flavor and medicinal properties. It is commonly used in cooking to add flavor to dishes, teas, and beverages. In herbal medicine, mint helps with digestion, relieves headaches, and soothes cold symptoms.",
                'cluture' =>"Mint is widely associated with freshness, both in terms of its flavor and aroma. It symbolizes rejuvenation, renewal, and a fresh start. Its cooling properties also make it a symbol of vitality and invigoration.",
                'pests' => json_encode(['Scale insects', 'Mealybugs', 'Spider mites']),
                'diseases' => json_encode(['Stem rot', 'Root rot']),

            ],
            [
                'name' => 'Tomato',
                'botanical_name' => 'Solanum lycopersicum',
                'scientific_name' => 'Solanum lycopersicum',
                'also_known_as' => json_encode(['Tomato', 'Wolf Peach']),
                'description' => 'The tomato is a red, juicy fruit commonly used as a vegetable in cooking. It grows on a vine and is known for its versatility in dishes like salads, sauces, and soups. Tomatoes are rich in vitamins, particularly vitamin C and lycopene, which are beneficial for health.',
                'genus_id'=> 2,
                'family_id'=>3 ,
                'order_id'=>2 ,
                'group_id'=>1 ,
                'phylum_id'=>2 ,
                'type_id'=>2 ,
                'drainage_id'=>1 ,
                'section_id'=>2,
                'toughness'=>"Medium",
                'maintenance'=>"Medium",
                'sunlight'=>"Full Sun",
                'hardness_zone'=>"2-11",
                'min_ph'=>5.5,
                'max_ph'=> 7.5,
                'min_tp' => 10,
                'ideal_min_tp' =>18,
                'ideal_max_tp'=>24,
                'max_tp' => 32,
                'water'=>"Every 3-4 Days",
                'repotting'=>"Every 1 Years",
                'fertilizer'=>"Every 2-3 Weeks",
                'misting'=>"Not Required",
                'pruning' =>'Regularly',
                'uses' => "Tomatoes are a staple in cuisines worldwide, used fresh in salads, cooked in sauces, soups, and stews, or processed into products like ketchup and paste. They are rich in antioxidants, particularly lycopene, which is linked to heart health and cancer prevention. Tomatoes are also used in skincare for their brightening and rejuvenating properties.",
                'cluture' =>"Tomatoes symbolize abundance, health, and vitality. They are often associated with Mediterranean cuisine and are a key ingredient in many cultural dishes, such as Italian pasta sauces and Spanish gazpacho. In some cultures, tomatoes are also seen as a symbol of love and passion due to their vibrant red color and historical nickname, 'love apple'. ", 
                'pests' => json_encode(['Aphids, ', 'Whiteflies', 'Tomato Hornworms']),
                'diseases' => json_encode(['Blight',  'Fusarium Wilt', 'Powdery Mildew']),

            ],

            [
                'name' => 'Cucumber',
                'botanical_name' => 'Cucumis sativus',
                'scientific_name' => 'Cucumis sativus',
                'also_known_as' => json_encode(['Cuke', 'Garden Cucumber']),
                'description' => 'Cucumbers are long, green vegetables with a high water content, making them refreshing and hydrating. They are commonly used in salads, pickles, and skincare routines. They are rich in vitamins K and C.  ',
                'genus_id'=> 3,
                'family_id'=>4 ,
                'order_id'=>3 ,
                'group_id'=>1 ,
                'phylum_id'=>2 ,
                'type_id'=>1 ,
                'drainage_id'=>1 ,
                'section_id'=>2,
                'toughness'=>"Medium",
                'maintenance'=>"Medium",
                'sunlight'=>"Full Sun",
                'hardness_zone'=>"4-12",
                'min_ph'=>5.5,
                'max_ph'=> 6.8,
                'min_tp' => 15,
                'ideal_min_tp' =>21,
                'ideal_max_tp'=>29,
                'max_tp' => 35,
                'water'=>"Every 2-3 Days",
                'repotting'=>"Every 1 Years",
                'fertilizer'=>"Every 3-4 Weeks",
                'misting'=>"Not Required",
                'pruning' =>'Regularly',
                'uses' => "Cucumbers are widely used in salads, sandwiches, and pickles. They are also used in skincare for their cooling and hydrating properties. Rich in water and low in calories, they are great for hydration and weight management.  ",
                'cluture' =>"Cucumbers symbolize freshness and purity due to their high water content and crisp texture. They are often associated with summer and healthy eating. In some cultures, they are used in spa treatments for their soothing properties.", 
                'pests' => json_encode(['Aphids, ', 'Cucumber Beetles']),
                'diseases' => json_encode(['Powdery Mildew',  'Downy Mildew']),

            ],

            [
                'name' => 'Carrot',
                'botanical_name' => 'Daucus carota',
                'scientific_name' => 'Daucus carota',
                'also_known_as' => json_encode(['Garden Carrot', 'Wild Carrot']),
                'description' => 'Carrots are root vegetables known for their bright orange color and sweet flavor. They are rich in beta-carotene, which is converted to vitamin A in the body. They are used in salads, soups, and as snacks.',
                'genus_id'=> 4,
                'family_id'=>5 ,
                'order_id'=>4 ,
                'group_id'=>1 ,
                'phylum_id'=>2 ,
                'type_id'=>1 ,
                'drainage_id'=>1 ,
                'section_id'=>2,
                'toughness'=>"Medium",
                'maintenance'=>"Medium",
                'sunlight'=>"Full Sun",
                'hardness_zone'=>"4-12",
                'min_ph'=>5.5,
                'max_ph'=> 6.8,
                'min_tp' => 7,
                'ideal_min_tp' =>15,
                'ideal_max_tp'=>24,
                'max_tp' => 30,
                'water'=>"Every 5-7 Days",
                'repotting'=>"Not Required",
                'fertilizer'=>"Every 4-6 Weeks",
                'misting'=>"Not Required",
                'pruning' =>'Not Required',
                'uses' => "Carrots are widely used in cooking, from salads to soups and stews. They are also eaten raw as a healthy snack. Rich in beta-carotene, they are excellent for eye health and boosting immunity.",
                'cluture' =>"Carrots symbolize health and vitality due to their nutritional benefits. They are often associated with good eyesight and are a staple in many cuisines worldwide. In some cultures, they are used in traditional remedies for their healing properties.", 
                'pests' => json_encode(['Aphids, ', 'Carrot Fly']),
                'diseases' => json_encode(['Leaf Blight',  'Root Rot']),

            ],


            [
                'name' => 'Bell Pepper',
                'botanical_name' => 'Capsicum annuum',
                'scientific_name' => 'Capsicum annuum',
                'also_known_as' => json_encode(['Sweet Pepper', 'Capsicum']),
                'description' => 'Bell peppers are colorful, crunchy vegetables available in green, red, yellow, and orange varieties. They are sweet in flavor and used in salads, stir-fries, and stuffed dishes. They are rich in vitamins A and C.',
                'genus_id'=> 3,
                'family_id'=>3 ,
                'order_id'=>2 ,
                'group_id'=>1 ,
                'phylum_id'=>2 ,
                'type_id'=>1 ,
                'drainage_id'=>1 ,
                'section_id'=>2,
                'toughness'=>"Medium",
                'maintenance'=>"Medium",
                'sunlight'=>"Full Sun",
                'hardness_zone'=>"4-12",
                'min_ph'=>5.5,
                'max_ph'=> 7.0,
                'min_tp' => 18,
                'ideal_min_tp' =>21,
                'ideal_max_tp'=>29,
                'max_tp' => 32,
                'water'=>"Every 3-4 Days",
                'repotting'=>"Every 1 Year",
                'fertilizer'=>"Every 2-3 Weeks",
                'misting'=>"Not Required",
                'pruning' =>'Regularly',
                'uses' => "Bell peppers are widely used in salads, stir-fries, and stuffed dishes. They are rich in vitamins A and C, making them great for boosting immunity and eye health. They are also low in calories, making them a healthy snack option.",
                'cluture' =>"Bell peppers are often associated with vibrant, healthy eating. They symbolize freshness and vitality due to their bright colors and crisp texture. In some cultures, they are used in festive dishes to add color and flavor.", 
                'pests' => json_encode(['Aphids, ', 'Thrips' , 'Whiteflies']),
                'diseases' => json_encode(['Blight',  'Bacterial Spot']),

            ],

        ];

        foreach ($plants as $plant) {
            Plant::create($plant);
        }
    }
}
